name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost:27017/nasa-database

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongo-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Setup Node.js Version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongo-version: ${{matrix.mongo-version}}

      - run: npm install
      - run: npm test
